version: "3"
services:
  nodejs:
    build: .
    env_file:
      - ".env"
    ports:
      - "$PORT:8080"
    links:
      - "mongo"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
  mongo:
    image: mongo:4.4
    env_file:
      - ".env"
    volumes:
      - "database:/data/db"

volumes:
  database:
    driver: local
